### ISSUE TITLE
Hardcoded stdlib dep causes problem

### ISSUE THREAD

**Issue by kinegg** [deligenius/multiparser#10]
Oak uses std 0.95.0, which means multiparser can't be used since it relies on 0.89. It just doesn't work.

This prevents us from making a necessary Deno upgrade

**Comment by gjuoun** [comment]
Sorry I've removed the oak support, unless the original Request is accessible from Oak

**Comment by gjuoun** [comment]
see updated oak usage in https://github.com/deligenius/multiparser#with-oak
